# roles/joomla/defaults/main.yml
---
# defaults file for joomla
joomla_directory: "/var/www/sites/joomla"
joomla_url: "https://downloads.joomla.org/cms/joomla5/5-1-4/Joomla_5-1-4-Stable-Full_Package.zip?format=zip"
